### ISSUE TITLE
Add Github "source version" metric

### ISSUE THREAD

**Issue by termeczky** [ICTU/quality-time#10011]
As a Quality-time user I want to to have access to "source version" so that track this metric within Quality-time

## Acceptance criteria

- [ ] A Quality-time user can add GitHub as source to a  "source version" metric.

## Assumptions

- Github exposes an endpoint to retrieve the GitHub version.

# Tasks

### Shared code

- [ ] Extend the example reports
- [ ] Indicate that GitHub supports the source version metric in the data model.

### Collector

- [ ] Add a GitHubSourceVersion collector in `source_collectors/github/source_version.py`.

## Documentation

- [ ] Update changelog
