### ISSUE TITLE
Add Github "unmerged branches" metric 

### ISSUE THREAD

**Issue by termeczky** [ICTU/quality-time#10012]
# User story

As a Quality-time user I want to to have access to "unmerged branches" so that track this metric within Quality-time

## Acceptance criteria

- [ ] A Quality-time user can add GitHub as source to the "unmerged branches"  metric

# Tasks

### Shared code

- [ ] Extend the example reports
- [ ] Add metric "unmerged branches" with GitHub as source to the data model

### Collector

- [ ] Add a GitHubUnmergedBranches collector in source_collectors/github/unmerged_branches.py.

## Documentation

- [ ] Update changelog
