### ISSUE TITLE
Add Github "source up-to-dateness" metric

### ISSUE THREAD

**Issue by termeczky** [ICTU/quality-time#10010]
# User story

As a Quality-time user I want to to have access to "source up-to-dateness" so that track this metric within Quality-time

## Acceptance criteria

- [ ] A Quality-time user can add GitHub as source to the "source up-to-dateness" metric.
  - [ ] Pipelines (see GitLab)
  - [ ] Files (see GitLab)

# Tasks

### Shared code

- [ ] Extend the example reports
- [ ] Add source Github to the "source up-to-dateness" metric in the data model.

### API-server

- [ ] No changes needed

### Collector

- [ ] Add a GitHubSourceUpToDateness collector in source_collectors/github/source_up_to_dateness.py.

## Documentation

- [ ] Update changelog
