### ISSUE TITLE
Add option to filter on (presence of) fix version for vulnerabilities

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#10323]
# User story

As a quality manager I want to filter security warnings by fix available and dependencies by update available so that I can have separate measures of security warnings, respectively dependencies, that can be fixed and cannot be fixed, respectively that can be updated and cannot be updated.

## Acceptance criteria

- [x] Security warnings with sources that supply information about the availability of fixes can be filtered by fix available.
- [x] As a quality manager I want to filter dependencies by update available so that I can have separate measures of dependencies that can be updated and cannot be updated.

## Out of scope:

No changes are needed for the dependencies metric because all dependencies sources either already support update status, or cannot support it:

- Composer dependencies: already has a **`latest_version_status`** parameter.
- Dependency-Track: already has a **`latest_version_status`** parameter for both dependencies and security warnings.
- npm dependencies: `npm outdated` only shows outdated dependencies.
- OWASP Dependency Check dependencies: no information on updates (at least not in Quality-time?!)
- pip dependencies: `pip list --outdated` only shows outdated dependencies.

The following security warnings sources are out of scope because they either already support filtering by fix status or cannot support it:

- Bandit security warnings: no information on fix versions
- Checkmarx CxCast: security warnings: no information on fix versions
- Dependency-Track: already has a **`latest_version_status`** parameter for both dependencies and security warnings.
- Generic JSON security warnings: no information on fix versions
- OpenVAS security warnings: no information on fix versions
- OWASP Dependency Check security warnings: no information on fix versions (at least not in Quality-time?!) 
- OWASP ZAP security warnings: no information on fix versions
- Pyupio Safety security warnings: no information on fix versions
- Sarif security warnings: no information on fix versions
- Snyk security warnings: no information on fix versions
- SonarQube security warnings: no information on fix versions

# Tasks

### Shared code

- [x] Add parameter "fix status" with values "security warnings with fix", "security warnings without fix", and placeholder "all security warnings" to:
  - [x] Anchore
  - [x] Anchore Jenkins plugin
  - [x] Cargo Audit
  - [x] Harbor security warnings. Note: no information on fix versions, only number of fixable warnings.
  - [x] Harbor JSON
  - [x] Trivy

### Collector

- [x] Change AnchoreSecurityWarnings collector to use the new parameter
- [x] Change AnchoreJenkinsPluginSecurityWarnings collector to use the new parameter
- [x] Change CargoAuditSecurityWarnings collector to use the new parameter
- [x] Change HarborJSONSecurityWarnings collector to use the new parameter
- [x] Change HarborSecurityWarnings collector to use the new parameter
- [x] Change TrivySecurityWarnings collector to use the new parameter

## Documentation

- [x] Update changelog

**Comment by fniessink** [comment]
@denniebouman, Please review the user story above. Thanks!

**Comment by denniebouman** [comment]
@fniessink review Done. 
I added also Harbor JSON, I wasn't sure if "Harbor" also included this? 
Is the HarborSecurityWarnings collector used for both Harbor and Harbor JSON? Or do we have to add the HarborJSONSecurityWarnings Collector to the list of Collectors?

**Comment by fniessink** [comment]
Nice catch. Harbor and Harbour JSON are two different collectors, so they indeed both need to be changed.
