### ISSUE TITLE
Add DevOps metric Mean Time to Repair

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3500]
# User story

As a quality manager I want to measure mean time to repair so that I can monitor the DevOps effectiveness of my team.

## Acceptance criteria

- [ ] Users can add an average issue lead time metric
- [ ] Users can configure Jira as source for the metric
- [ ] Users can configure Azure DevOps as source for the metric

## Assumptions

- This metric can be implemented using the existing [Lead time for changes](https://quality-time.readthedocs.io/en/latest/reference.html#lead-time-for-changes) metric that we're going to rename.

## Open issues

- None so far.

## Out of scope

- GitLab issues as source

# Tasks

- [ ] Rename the "lead time for changes" metric to "average issue lead time".

## Documentation

- [ ] Update changelog
- [ ] Add explanation to the user manual that the DORA metrics "lead time for changes" and "mean time to repair" can both be measured using the "average issue lead time" metric.
