### ISSUE TITLE
Automatically remove accepted technical debt when all tracked issues for a metric are resolved

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#3935]
# User story

As a quality manager I want Quality-time to ignore accepted technical debt if the metric has linked issues that are all resolved so that the metric turns red if the issues did not fix the metric.

This works similar to the technical debt end date: as soon as the technical debt end date is in the past, the fact that technical debt is accepted is ignored and the metric is no longer grey if it doesn't meet its target. Likewise, as soon as all linked issues are resolved, the fact that technical debt is accepted will be ignored and the metric will no longer be grey if it doesn't meet its target

Note: This requires Quality-time to understand the status/resolution of issues. In case of Jira, use the builtin issue resolution field, not the status field that can be (and is) freely changed.

## Acceptance criteria

- [x] A metric with accepted technical debt that has issues that are all resolved ignores the technical debt status.

## Assumptions

- An issue tracker has been configured
 
## Open issues

- Is the text in the UI (see below) clear enough?

## Out of scope

- Changing the technical debt status (we don't do that when the technical debt end date passes either).
- Making this configurable. Since we moved the issue fields to a technical debt tab in #4165 it is clear issues and technical debt are related.

# Tasks

### Frontend

- [x] Show the issue status category (todo, doing, done) as label color.
- [x] If the metric has accepted technical debt, the target column includes a popup with the debt target. 
- [x] If the metric has accepted technical debt that is being ignored, the target column popup shows why it is ignored.

###  Shared python

- [x] Change `def accept_debt_expired(self) -> bool` in  `components/shared_python/src/shared/model/metric.py` to also return true if all metric issues have been resolved.
 
### Collector

- [x] Change `collector` to also collect issue status (open/closed) in `components/collector/src/source_collectors/jira/issue_status.py`.

## Feature tests

- [x] Create a metric that doesn't meet its target, has accepted technical debt and resolved issues, and check that its status is `target_not_met`.

## Documentation

- [x] Update changelog
- [x] Add instruction to user manual
  - [x] Mention technical debt status under [Editing metrics](https://quality-time.readthedocs.io/en/latest/usage.html#editing-metrics)
