### ISSUE TITLE
Add metric with current checked version of code

### ISSUE THREAD

**Issue by MaxStaallekker** [ICTU/quality-time#3981]
Currently Quality-Time doesn't show which version of the code is being checked in SonarQube, like v 1.1567 or 2.4676.
I'd like a metric that shows that. Would be nice to be able to show that from different sources like SonarQube, Checkmarx, OWASP ZAP, etc.

# User story

As a quality manager I want to 'measure' the version of the software analyzed by tools so that I can check whether the tool is actually analyzing the expected version of the software.

# Acceptance criteria

The story is considered complete if:
- [x] The user can add a metric 'software version'
- [x] The user can add sources to the 'software version' metric that have information about the software version.

Currently, the only sources that seem to have information about the software version being analyzed are SonarQube and the Performancetest-runner.

# Tasks

###  Shared python

- [x] Change the data model
  - [x] Add new metric
  - [x] Make sources support the metric 
    - [x] SonarQube 
    - [x] Performancetest-runner 
- [x] Update the example reports 
  - [x] SonarQube
  - [x] Performancetest-runner 

### Collector

- [x] Add collectors for the 'software version' metric
  - [x] Add SonarQube collector
  - [x] Add Performancetest-runner collector

## Documentation

- [x] Update changelog
  - [x] Mention metric
  - [x] Mention all sources supporting the metric
    - [x] SonarQube  
    - [x] Performancetest-runner 

# Out of scope

- Getting the target value for the metric from a source (e.g. GitLab). There's another issue for that: #2924.

**Comment by fniessink** [comment]
What would the target for this metric look like? When is the target met and when not? Or, same question worded differently: in what circumstances should Quality-time complain/warn you about the analyzed source code version?

**Comment by MaxStaallekker** [comment]
It doesn't necessarily need a target, just show which version it is. One possibility is to check the version that is being scanned in SonarQube against the version that is present in Gitlab for instance or any other source that you can select as "most recent".

**Comment by fniessink** [comment]
Right, so we really need to implement "information metrics" first (#2051), because for this metric a target value does not make sense.

I didn't read it carefully enough first, but what you're actually describing here is getting the target for the metric from a source (GitLab in your example). We have a different issues for that: #2924.
