### ISSUE TITLE
Support Quality-time as source for the remediation effort metric

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4074]
# User story

As a product owner or project leader I want to know how much technical debt my software has so I can better plan my project and/or backlog.

## Acceptance criteria

- [ ] The user can add Quality-time reports/subjects/metrics as source for the remediation metric
- [ ] Quality-time has default remediation effort per measurement entity  
- [ ] The default remediation effort can be changed per metric

## Assumptions

- Something is present...

## Open issues

- How do we prevent a false sense of precision ("The total technical debt remediation effort needed is 123 hours, 5 minutes, and 10 seconds")? 
  - Maybe use orders of magnitude
  - Use ranges 

## Out of scope

- Refactoring ...
- Adding ...

# Tasks

### Frontend

- [ ] Add `user interface element`
- [ ] Update `user interface element`

###  Shared python

- [ ] Change the data model
- [ ] Change endpoint `endpoint`
- [ ] Extend the example reports

### External server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

### Collector

- [ ] Change `collector`
- [ ] Add ...

### Notifier 

- [ ] Change `destination`
- [ ] Add ...

### Internal server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

## Feature tests

- [ ] `role` does `action`
- [ ] ...

## Documentation

- [ ] Update changelog
  - [ ] Describe change
  - [ ] Add deployment instructions to changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots
- [ ] Update deployment instructions
- [ ] Update software documentation

Reported by @Sebastiaan127001
