### ISSUE TITLE
Show relevant issue info in the issue column

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4186]
# User story

As a quality manager I want to see date-related information on issue in Quality-time so I understand when an issue is supposed to be resolved.

## Acceptance criteria

The issue card and popup include the following information:
- [x] Active sprint, if the issue has one, including
  - [x] name 
  - [x] state (active/future/...)
  - [x] end date (displayed as date and days remaining)
- [x] Release, if the issue is assigned to a release, including
  - [x] release name
  - [x] release version
  - [x] planned release date (fix version in Jira and/or version, displayed as date and days remaining)
- [x] Issue due date (displayed as date and days remaining)

## Out of scope

- Updating the technical debt end date based on the information listed above
- Ignoring technical debt when one or more of the dates listed above pass

# Tasks

### Frontend

- [x] Add information to issue cards in the issue column (but not by default)
- [x] Make information elements listed above configurable via the settings (the same how summary, creation date, and update date are configurable already)
- [x] Add information to issue cards popups

### Collector

- [x] Change the `IssueStatus` class to include the information listed above
- [x] Change the Jira issue status collector to parse the information listed above

## Documentation

- [x] Update changelog
- [x] Check whether user manual needs to be updated
- [x] Check whether screenshots need to be updated
