### ISSUE TITLE
Report on metric reaction times

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4190]
# User story

As a quality manager I want to report on the timeliness of actions in response to metrics not meeting their targets so I can show to management and clients that the quality management process is functioning adequately even if metrics themselves may not be meeting all their targets at a specific moment in time. 

## Acceptance criteria

- [x] Quality-time shows per metric how much time is left to react
- [x] The required reaction times can be set per metric status

## Assumptions

- No new data, except for the required reaction times, needs to be stored in the database. We already keep track of the status start date.

## Open issues

- Exact text of the popup.

## Related issues

- #4327

## Out of scope

- Making response time configurable per metric, subject, etc.
- Having a different required response time for metrics that become red with/without accepted technical debt 
- Reporting historic response times over a period of time.
- Taking working days/weekends into account

# Tasks

### Frontend

- [x] Add a new report configuration tab "Expected reaction times"
  - [x] Add a field for each status (except green, blue, and grey) to set a required reaction time in days, defaults red = 7 days, yellow = 21 days, white = 3 days
- [x] Add a reaction time column to the metrics table: "Time left to react"
  - [x] If the status is red, yellow, or white, show the time left in days 
    - [x] If the time left is negative, show "0" with a red background semantic ui Label
    - [x] The cell has a popup with a text like "The status is X. You have Y days left to address this metric. Change the reaction times in the report header"
  - [x] If the metric status is green, grey (without end date) or blue, leave empty.
  - [x] If the metric status is grey with an end date, show that.
  - [x] Make sure the column can be hidden via de settings panel.
  - [x] Make sure the column can be sorted.

### External server

- [x] Use the `/api/v3/report/<report_uuid>/attribute/<report_attribute>` endpoint to set the expected reaction times using the attribute names `expected_reaction_time_white`, `..._red` and `...yellow`. So, no changes required to the external server.

## Documentation

- [x] Update changelog
- [x] Add instruction to user manual
- [x] Update screenshots

**Comment by Sebastiaan127001** [comment]
#vote
