### ISSUE TITLE
Create separate shared python component with only the data model

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4199]
This will allow the notifier and collector component to have the data model installed as python package instead of having to download it from the internal server.

# Tasks

- [x] Create shared data model component by copying shared python 
  - [x] Update Circle CI config
  - [x] Update GitHub Actions config
  - [x] Remove all non-data model code from shared data model
- [x] Update shared python 
  - [x] Use shared data model in shared python code
  - [x] Remove data model from original shared python
  - [x]  Move utility functions now only used by the external server to the external server
- [x] Update external server
  - [x] Use shared data model in external server python code
  - [x] Include shared data model in external server docker image
  - [x] Move utility functions now only used by the external server to the external server
- [x] Update internal server
  - [x] Use shared data model in internal server python code
  - [x] Include shared data model in internal server docker image
  - [x] Remove internal server data model endpoint
- [x] Update collector
  - [x] Import shared data model in collector instead of downloading it
- [x] Update notifier
  - [x] Import shared data model in notifier instead of downloading it
- [x] Update docs
  - [x] Update generation of reference docs to use shared data model instead of shared python 
  - [x] Update software documentation
  - [x] Update developer documentation

# Out of scope/future work

- Using the Pedantic version of the data model in the collector and notifier instead of loading the JSON-version
- Using the imported version of the data model in the internal server instead of retrieving it from the database
