### ISSUE TITLE
Accept technical debt and change technical debt value in one user action

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4493]
# User story

As a quality manager I want the technical debt value to be set to the current measurement value when I accept technical debt because in 90% of the cases that is the technical debt value that I want to set anyway. Similarly, when I no longer accept technical accept, I want the technical debt value and the end date to be cleared.

## Acceptance criteria

- [ ] An existing technical debt value is overwritten when technical debt is accepted.
- [ ] An existing technical debt value and an existing technical debt end date are removed when technical debt is no longer accepted
- [ ] If there is no current measurement value and the user accepts technical debt, then the technical debt value is set to 0.

## Out of scope

- Changing the technical debt end date.

# Tasks

### Frontend

- [ ] Change "Yes" to "Yes / Also set the technical debt value to the current measurement value"
- [ ] Change. "No" to "No / Also remove the technical debt value and clear the technical debt end date"

### Shared server code

- [ ] Change endpoint `endpoint`

### External server

- [ ] Change metric endpoint to also change the technical debt value and technical debt end date when technical debt is accepted.

## Feature tests

- [ ] Add/change feature tests for changing technical debt

## Documentation

- [ ] Update changelog
- [ ] Add instruction to user manual

**Comment by fniessink** [comment]
Duplicated by #5127 and #5129.
