### ISSUE TITLE
Show the amount of time the desired reaction time was not met

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4538]
# User story

As a quality manager I want to show my manager and client whether metrics are reacted to in time so it's either clear the team is responding timely or that improvement actions are needed.

Quality-time shows per metric how many days, in the displayed period, metric desired reaction times were overrun. 

Suppose the desired reaction time for a red metric is three days. Then:
- If a metric is never red in the displayed period, the reaction time overrun is zero days
- If a metric is red for two days in the displayed period, the reaction time overrun is still zero days
- If a metric is red for four days in the displayed period, the reaction time overrun is one day
- If a metric is red for four days and then later for five days, the reaction time overrun is three days

## Acceptance criteria

- [ ] When the number of dates visible is > 1 then Quality-time shows the amount of time that metrics were not reacted to in time
- [ ] The time period is determined by the number of dates and the time between dates visible.

## Out of scope

- Averaging multiple metrics.
- Overrunning a desired reaction time for a red metric may be considered worse than overrunning a desired reaction time for a yellow metric. However, since the desired reaction time for a yellow metric can be made longer than the one for red metrics (and is longer by default), we assume overrunning the yellow reaction time is as bad as overrunning the red reaction time.
- Showing how often the deadline was missed. For the time being we assume that fixing issues in a timely manner is more important than how often a deadline is missed.
- Notifier notifying about (missed) deadlines.

## Open issues

- Can the overrun be calculated in the frontend or do we need to change the backend as well?

# Tasks

### Frontend

- [ ] Add column "Reaction time overrun" / "Amount of days the desired reaction times were overrun in the period <X>-<Y>"
- [ ] Show the column in the settings panel.

### External server

- [ ] Change GET report endpoint: include number of days overrun in the summary (if overrun cannot be calculated easily in the frontend)

## Feature tests

- [ ] Check overrun (if backend is changed to return number of days overrun)

## Documentation

- [ ] Update changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots
- [ ] Update software documentation

Reported by @Sebastiaan127001
