### ISSUE TITLE
Add a default epic link to Jira issues created from Quality-time

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#4614]
# User story

As a  quality manager I want to have issues created from Quality-time to have a default epic link so I can find them in one place in the issue tracker.

## Acceptance criteria

- [ ] New issues have the configured epic link in the issue tracker.

## Assumptions

- Projects have a limited number of epics that we can present in a single choice combobox.

## Out of scope

- Pagination on the epics returned by the issue tracker.
- Showing the issue epic link in the issue cards in the Issues column.
- Dealing with changes in the issue tracker after it has been configured (e.g. issue types disappearing). If this happens, the user may see a client error. We'll deal with this if it happens frequently enough.
 
## Related issues

- #4468

# Tasks

### Frontend

- [x] Add epic link single choice field that contains the epics belonging to the selected project. Field is not mandatory and allows None as choice.
- [x] If the current issue type does not support epic links, show a yellow warning below the field with the title "Epic links not supported" and the text "The issue type '<issue type>' in project '<project key>' does not support linking issues to an epic when creating issues, so new issues will not be linked to an epic."

### External server

- [x] Retrieving the options: Extend issue tracker code to get epic links and return them as options in `def get_options(self) -> Options`. Extend the Options model to include epic links. Query the issue meta data to check whether epic links are allowed for the currently selected project and issue type.
- [x] Creating the issue: add an epic link if an epic link is configured and  epic links are allowed for the currently selected project and issue type:
```python
if epic_link and self.__epi_links_supported():  # pragma: no cover-behave
    json["fields"]["epic_link"] = self.__get_epic_link_somehow()
```

## Feature tests

- [x] Configure epic link in report.
- [x] Attempt to create an issue

## Documentation

- [x] Update change-log
- [x] Add instruction to user manual
- [x] Update screenshots (probably not needed)
