### ISSUE TITLE
Source parameter layout

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4623]
# User story

As a quality manager I want a logical layout of source parameters so I am not confused by all the parameters I may have to configure for a source.

## Acceptance criteria

- [ ] Parameters can be grouped and this is visible in the UI.
- [ ] (Groups of) parameters can be mutually exclusive.

## Assumptions

- Something is present...

## Open issues

- Split this into two stories?

- How does the data model codify the mutual exclusiveness of parameters and parameter groups. Maybe something like this:

```python
METER_JSON = Source(
    name="JMeter JSON",
    description=JMETER_DESCRIPTION,
    url=JMETER_URL,
    parameters=dict(
        test_result=TestResult(values=["failed", "success"]),
        transaction_specific_target_response_times=TRANSACTION_SPECIFIC_TARGET_RESPONSE_TIMES,
        foo_parameters=dict(
            response_parameters=dict(
                target_response_time=TARGET_RESPONSE_TIME,
                response_time_to_evaluate=RESPONSE_TIME_TO_EVALUATE,
            ),
            transaction_filters=dict(
                parameters=dict(
                    transactions_to_ignore=TRANSACTIONS_TO_IGNORE,
                    transactions_to_include=TRANSACTIONS_TO_INCLUDE,
                ),
                label="Transaction filters",
                mutually_exclusive=True,  # To specifiy mutual exclusive parameters within a group
            ),
            mutually_exclusive=True
        ),
        **access_parameters(JMETER_JSON_METRICS, source_type="JMeter report", source_type_format="JSON"),
    ),
    entities=ENTITIES,
)
```

## Out of scope

- Refactoring ...
- Adding ...

# Tasks

### Frontend

- [ ] Add `user interface element`
- [ ] Update `user interface element`

### Shared data model

- Split the parameters in groups:
  1. Access parameters (URL, landing URL, username, password, token)
  2. 

### Shared server code

- [ ] Change endpoint `endpoint`
- [ ] Extend the example reports

### External server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

### Collector

- [ ] Change `collector`
- [ ] Add ...

### Notifier

- [ ] Change `destination`
- [ ] Add ...

### Internal server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

## Feature tests

- [ ] `role` does `action`
- [ ] ...

## Documentation

- [ ] Update changelog
  - [ ] Describe change
  - [ ] Add deployment instructions to changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots
- [ ] Update deployment instructions
- [ ] Update software documentation
