### ISSUE TITLE
Jira audit trail

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4743]
# User story

As security officer I want Quality-time to note who creates an issue in the issue tracker so that creating issues is non-repudiationable.

## Acceptance criteria

- [x] Issues created in the issue tracker contain the LDAP username and email address of the user who created the issue from Quality-time in the description.

## Assumptions

- Users may have the right to change the description of issues in the issue tracker but the issue tracker keeps the old version of the description so that there is always a way to find out who created the issue.
- We don't assume that users have the same username in LDAP and in the issue tracker, so we don't @-mention the user in the description.

# Tasks

### External server

- [x] Change endpoint `api/v3/metric/<metric_uuid>/issue/new` to add "This issue was created by {username } {email address}." in `create_issue_description(metric, subject, report) -> str` in `components/external_server/src/routes/metric.py`
- [x] Change the auth plugin in the external server to pass the username and email address to the wrapped end point if the endpoint indicates it needs the user data via een boolean flag. For example:

```python
@bottle.post("/api/v3/metric/<metric_uuid>/issue/new", permissions_required=[EDIT_REPORT_PERMISSION], pass_user=True)
def add_metric_issue(metric_uuid: MetricId, database: Database, user: User):
    ...
    issue_description = create_issue_description(metric, subject, report, user)
    ...
```

## Documentation

- [x] Update changelog
