### ISSUE TITLE
Better issue summary for issues created from Quality-time

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4747]
# User story

As a quality manager I want Quality-time to give newly created issues in the issue tracker a more specific summary than "Quality-time metric {metric name}" so that it is clear for developers what they have todo to fix the metric.

## Acceptance criteria

- [x] The Jira summary should contain: `Fix {number} {unit} from {source name}`

- [x] The Jira issue description should contain: 

```
The metric {metric} in Quality-time reports {number} {unit} from {source name}.

Please go to {source URL} for more details.
```

Note that there can be multiple source URLs.

# Tasks

### External server

- [x] Change the issue creation code

## Documentation

- [x] Update changelog
  - [x] Describe change
- [x] Add instruction to user manual

Reported by @Sebastiaan127001

**Comment by Sebastiaan127001** [comment]
@fniessink can we please combine this with the number of warnings (or other units) like the following. And ideally, the description should have a link to the source, so that the Jira user can omit Quality-time and go directly to the issue.

**Jira issue summary:** 
Fix {number} {unit} from {source name}

**Jira issue description:** 
The metric {metric} in Quality-time reports {number} {unit} from {source name}.

Please go to {source URL} for more details.

**Comment by Sebastiaan127001** [comment]
%VOTE
