### ISSUE TITLE
Make SonarQube quality-gate status visible in Quality-time

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4748]
# User story

As a developer I want to see the SonarQube quality gate status in Quality-time so I know whether we have met its criteria without having to navigate to SonarQube.

## Acceptance criteria

- [ ] `role` can `action`

## Assumptions

- Something is present...

## Open issues

- What do we need to ...

## Out of scope

- Refactoring ...
- Adding ...

# Tasks

### Frontend

- [ ] Add `user interface element`
- [ ] Update `user interface element`

### Shared data model

- [ ] Add subject `subject` to the data model
- [ ] Add metric `metric` to the data model
- [ ] Add source `source` to the data model
- [ ] Add logo for source `source`

### Shared server code

- [ ] Change endpoint `endpoint`
- [ ] Extend the example reports

### External server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

### Collector

- [ ] Change `collector`
- [ ] Add ...

### Notifier

- [ ] Change `destination`
- [ ] Add ...

### Internal server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

## Feature tests

- [ ] `role` does `action`
- [ ] ...

## Documentation

- [ ] Update changelog
  - [ ] Describe change
  - [ ] Add deployment instructions to changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots
- [ ] Update deployment instructions
- [ ] Update software documentation

Reported by @Sebastiaan127001
