### ISSUE TITLE
Jira issue tracker personal access token remaining lifespan

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4828]
# User story

As a quality manager I want Quality-time to warn me when the PAT configured for the Jira issue tracker is about the expire so I can renew it on time.

## Acceptance criteria

- [ ] `role` can `action`

## Assumptions

- Something is present...

## Open issues

- What do we need to ...

## Out of scope

- Refactoring ...
- Adding ...

# Tasks

### Frontend

- [ ] Add `user interface element`
- [ ] Update `user interface element`

### Shared data model

- [ ] Add subject `subject` to the data model
- [ ] Add metric `metric` to the data model
- [ ] Add source `source` to the data model
- [ ] Add logo for source `source`

### Shared server code

- [ ] Change endpoint `endpoint`
- [ ] Extend the example reports

### External server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

### Collector

- [ ] Change `collector`
- [ ] Add ...

### Notifier

- [ ] Change `destination`
- [ ] Add ...

### Internal server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

## Feature tests

- [ ] `role` does `action`
- [ ] ...

## Documentation

- [ ] Update changelog
  - [ ] Describe change
  - [ ] Add deployment instructions to changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots
- [ ] Update deployment instructions
- [ ] Update software documentation

## Other information

Requested by @eric-nieuwland.

Jira docs: https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

**Comment by fniessink** [comment]
Duplicate of #4827.
