### ISSUE TITLE
Web site certificate remaining lifespan

### ISSUE THREAD

**Issue by eric-nieuwland** [ICTU/quality-time#4829]
# User story

As a DevOps engineer I want to see the remaining lifespan of web site's certificate so I can timely renew the certificate.

## Acceptance criteria

- [ ] DevOps engineer can specify web site's URL
- [ ] Quality-time can obtain the web site's certificate
- [ ] Quality-time can determine the remaining lifespan of the certificate

## Assumptions

- Only needs to work for web sites that do have a certificate
- Certificates always have an expiry date

## Open issues

- What do we need to ...

## Out of scope

- Refactoring ...
- Adding ...

# Tasks

### Frontend

- [ ] Add `user interface element`
- [ ] Update `user interface element`

### Shared data model

- [ ] Add subject `subject` to the data model
- [ ] Add metric `metric` to the data model
- [ ] Add source `source` to the data model
- [ ] Add logo for source `source`

### Shared server code

- [ ] Change endpoint `endpoint`
- [ ] Extend the example reports

### External server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

### Collector

- [ ] Change `collector`
- [ ] Add ...

### Notifier

- [ ] Change `destination`
- [ ] Add ...

### Internal server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

## Feature tests

- [ ] `role` does `action`
- [ ] ...

## Documentation

- [ ] Update changelog
  - [ ] Describe change
  - [ ] Add deployment instructions to changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots
- [ ] Update deployment instructions
- [ ] Update software documentation

**Comment by fniessink** [comment]
I'm not sure this should be within the scope of Quality-time. Aren't tools like Nagios or Zabbix better equipped to monitor this? See for example https://www.nagios.com/solutions/ssl-certificate-monitoring/ and https://www.zabbix.com/integrations/ssl.
