### ISSUE TITLE
Web site certificate remaining lifespan

### ISSUE THREAD

**Issue by eric-nieuwland** [ICTU/quality-time#4830]
# User story

As a DevOps engineer I want Quality-time to warn me when the certificate of a web site is about the expire so I can renew it on time.

## Acceptance criteria

- [ ] DevOps engineer can specify the web site's URL
- [ ] DevOps engineer can specify the length of the warning period

## Assumptions

- Sufficient to evaluate the certificate's expiry once per hour (or even once per day)
- To avoid alarming web site's security should not request the certificate too often

## Open issues

- What do we need to ...

## Out of scope

- Refactoring ...
- Adding ...

# Tasks

### Frontend

- [ ] Add `user interface element`
- [ ] Update `user interface element`

### Shared data model

- [ ] Add subject `subject` to the data model
- [ ] Add metric `metric` to the data model
- [ ] Add source `source` to the data model
- [ ] Add logo for source `source`

### Shared server code

- [ ] Change endpoint `endpoint`
- [ ] Extend the example reports

### External server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

### Collector

- [ ] Change `collector`
- [ ] Add ...

### Notifier

- [ ] Change `destination`
- [ ] Add ...

### Internal server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

## Feature tests

- [ ] `role` does `action`
- [ ] ...

## Documentation

- [ ] Update changelog
  - [ ] Describe change
  - [ ] Add deployment instructions to changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots
- [ ] Update deployment instructions
- [ ] Update software documentation

**Comment by fniessink** [comment]
Duplicate of #4829.
