### ISSUE TITLE
⭐️ Future Issues for pre-refinement

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#4959]
Project requests
- [x] I recently had a project (E) request to trigger the refresh of a metric or at least have an indication of which metric is being refeshed currently. See also https://github.com/ICTU/quality-time/issues/3134
- [x] project G requested me to show the number of realised issues in the last sprint (this is not possible though JQL, but the info is available). Another use case for this came from project F:
As a quality manager, I would like to see the percentage of issues with label X that have been part of the previously closed sprint. (what percentage were tech debt stories?). This should become possible when #5098 is implemented.
- [x] Several of my project face the problem of running out of nexus storage during software development. Can we add a collector to fetch the percentage of used storage on a Nexus host? No, is monitoring; outside scope Quality-time. There is an issue in progress to add this to the development platform at ICTU (IES-5817).
- [x] #5117
- [x] #5118

New improvement ideas
- [x] #5119
- [x] #5120
- [x] #5121
- [ ] in relation to make Quality-time a more mature report (https://github.com/ICTU/quality-time/issues/4069) I would be useful to have the option for the user to use variables in the comment field. For this we need a section to store the placeholders and the related text. Like <link-to-jira> = "https://jira.organisation.com/". Unfortunately, Quality-time uses HTML for comments at the moment which doesn't support variables. One alternative may be to switch to Markdown for comments and investigate whether Markdown variables may offer a solution. See https://www.brianchildress.co/variables-in-markdown/.
- [x] #5122: We will add extra subject types to #3130 to add "system" or "infrastructure" as possible product type.
- [x] #5123
- [x] supply a functionality to erase all technical debt of a certain metric in one click. This could be one button that sets yes to no, deletes the related issue and deletes the end date and the accepted amount. See #5125.
- [x] build collector for mocha so that Quality-time can read mochaweome.json which shows Cypress test results. @Sebastiaan127001 checks whether the JUnit report of Cypress can be used instead.
- [x] In relation to this issue: https://github.com/ICTU/quality-time/issues/4931 SonarQube can be a compound metric too. Violations versus the separate violations like 'long units'. The metrics for specific violation types ('long units', 'too many parameter', etc.) already support the percentage scale. The violations metric does not. Note that the percentage scale for the violations metric only makes sense when filtering violations by type or severity otherwise the percentage is always 100%.
- [x] #5128
- [x] apart from filtering measurement entities, it would be useful to be able to filter results in general, this might fix the version problem, see also https://github.com/ICTU/quality-time/issues/3328#issuecomment-1363018909
- [x] #5129
- [ ] Create feature request to accept version numbers with postfix parts. Supply a few examples of version numbers that currently fail.

**Comment by Sebastiaan127001** [comment]
@fniessink as promised, I hereby include a list of software versions that development teams use, but that do not match the semver / pep standard and therefore break the software version metric.

team F
230216.post60271390
230215-a217ad48
230208-4806c8d0


team E
0.0.38.0
0.37.0
1.7.61.0-SNAPSHOT

Does this help you to improve the metric?

**Comment by Sebastiaan127001** [comment]
@fniessink as promised. I have discussed with the team the benefits of Mocha Awesome test reporter compared to JUnit. The team (G) stated that both reports contain the same information that Quality-time needs. The team advises, however, to, eventually, create a collector for the Mocha Awesome JSON since this is the standard for Cypress. The JUnit format was initially intended for unit test reports.
