### ISSUE TITLE
Remove internal server

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#5822]
This issue is blocked by #5789 and #5790.

# Tasks

### Shared server code

- [ ] Move all code to the external server

### Internal server

- [ ] Remove code
- [ ] Update compose files

## Feature tests

- [ ] Remove feature tests that test the internal server

## Documentation

- [ ] Update changelog
  - [ ] Describe change (this is a breaking change, so next version of Qt is a major version change)
  - [ ] Add deployment instructions to changelog
- [ ] Update deployment instructions
- [ ] Update software documentation
