### ISSUE TITLE
Allow for creating issues for specific entities 

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#5955]
# User story

As a quality manager I want to create issues for specific measurement entities so that I can keep track of which issues are meant to address which entities. For example, when there are different security warnings for different container images, it may be needed to create multiple issues because different people/teams have to fix the different warnings.

## Acceptance criteria

- [x] The user can create one or more issues for a specific measurement entity. 
- [x] Quality-time displays the issue identifier alongside the measurement entity.
- [x] Quality-time displays the status of the issue alongside the measurement entity.
- [x] Quality-time also displays the issue identifiers of issues created for specific measurement entities in the "Technical debt" tab.
- [ ] When creating the issue, the status of the entity is changed to "confirmed"
- [ ] When creating the issue, the measurement entity status end date is set to the desired response time for "confirmed" (see #5099).
- [ ] When the issue is closed, the measurement entity status (assuming the entity still exists) is set to unconfirmed. Note: the end date is *not* reset.
- [x] The issues created for the entities are visible in the issues column of the metric (together with any other issues created for the metric).
- [x] The visible issue details that can be set via the Settings are also applied to the issue cards alongside the measurement entities.
- [ ] If a measurement entity with linked issue(s) disappears, the linked issue is no longer visible in the measurement entity table (because the entity has disappeared), but the issue is still listed in the "Technical debt" tab.
- [ ] The issue text in Jira contains a link to the measurement entity (e.g. a violation) in the source (e.g. SonarQube).

## Assumptions

- #5099 is implemented first.

## Out of scope

- Setting the desired response time on issues in the issue tracker.
- Creating one issue for multiple measurement entities.

# Tasks

### Frontend

- [ ] In the measurement entity detail accordion, add an extra line with:
  - [ ] "Create issue" button (left) 
  - [ ] "Issue links" field (right)
- [ ] Add a column with `<IssueStatus>` to the measurement entity table (rightmost column)

### External server

- [ ] Change endpoint `add_metric_issue`: register link between issue id and measurement entity key
- [ ] Change endpoint `post_metric_attribute`: change links where necessary.

## Feature tests

- [ ] Add test if necessary

## Documentation

- [ ] Update changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots
- [ ] Update software documentation
