### ISSUE TITLE
Show first seen timestamp of measurement entities

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#6351]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the dev team asks me what had changed when looking at a metric that reports more issues that yesterday. For instance, the number of security warnings metric having OWASP dependency-check as a source. Regularly, the tool reports new CVE's and adds them to the list. Currently, Quality-time does not show, in the measurement entities tab, which warnings are new since today.

**Describe the solution you'd like**
It would be useful if the entities table also had a column with a 'first reported date'.

**Tasks**

- [x] Keep track of the first seen timestamp in the metric data. 
- [x] Copy the timestamp when adding a new measurement for the same metric (like we copy the user data).
- [x] Add a column to the measurement entity table "First seen" (make sure it sorts correctly).
- [x] Implement this generically for all metrics with entities.
- [x] When there is no first seen date, make the column cell empty.

Out of scope:
- Make sure the measurement entities column is sorted by "First seen" (descending) by default. See #6644.

   
<img width="1628" alt="image" src="https://github.com/ICTU/quality-time/assets/95095453/e03fba8a-819f-4f46-9cbc-6a0eeb87a3af">
