### ISSUE TITLE
Duration of pipelines

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#6423]
# User story

As a developer I want to track the duration of my pipeline so that I prevent it from taking too much time.

## Acceptance criteria

- [x] User can add a metric "CI-pipeline duration" 
- [x] Users can add Jenkins as source.
  - [x] User can select a pipeline and branch to monitor (making the metric working for jobs is nice to have). 
- [x] Users can add GitLab CI as source.
   - [x] User can select a pipeline and branch to monitor.
- [x] Users can add Azure DevOps as source.
   - [x] User can select a pipeline and branch to monitor.

## Scope

- [x] The metric can be used to measure the duration of exactly one pipeline.

## Out of scope

- [ ] Quality-time measures the duration of the complete pipeline and shows the stages as measurement entities, with the duration per stage.
- [ ] Users can ignore/include stages by name.
- [ ] #12180
- [x] #12181

# Tasks

### Shared code

- [x] Add metric `CI-pipeline duration` to the data model
- [x] Change `Jenkins` to support the new metric 
- [x] Change `Azure DevOps` to support the new metric 
- [x] Change `GitLab CI` to support the new metric 

### Collector

- [x] Add JenkinsPipelineDuration collector. For Jenkins the [`wfapi`](https://github.com/jenkinsci/pipeline-stage-view-plugin/blob/master/rest-api/README.md) can be used.
- [x] Add AzureDevopsPipelineDuration collector
- [x] Add GitLabPipelineDuration collector

## Documentation

- [x] Update changelog

**Comment by Sebastiaan127001** [comment]
Duplicated by #5348 ?

**Comment by wkoot** [comment]
Open problem: mixing more than one source on the PipelineDuration metric produces metric result of only one source, even when multiple the entities are correctly collected per source
Also: the Jenkins pipeline duration source does not specify a pipeline_selection parameter like the GitLab source, which may be desirable
For now I think we also need to disregard Azure DevOps pipeline runs which were pending admin input (first time run only) for permission to run.. the data returned from de API does not provide an option to detect this
