### ISSUE TITLE
Add delta column

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#7039]
# User story

As a quality manager I want to see the difference between measurements made at two or more dates.

## Acceptance criteria

- [ ] User can turn delta's on and off via the settings panel
- [ ] The delta setting is included in the URL parameter
- [ ] When showing multiple dates a delta column is added between each pair of dates, showing the delta between each pair of dates
- [ ] The delta column shows the measurement difference as:
  - [ ]  "+&lt;number&gt;" or "-&lt;number&gt;" in case of count and percentage scale (note that the percentage delta is not a percentage)
  - [ ]  "lower", "equal", "higher" in case of version numbers
- [ ] The delta column display the delta using a green label if the measurement is better and a red label if it's worse, no label if it's equal. 
- [ ] The delta column header is "Change"

## Nice to have

- [ ] When showing one date, a delta column is added, showing the delta with yesterday's latest measurements

## Assumptions

- No changes needed to the API.

## Open issues

- What do we need to ...

# Tasks

### Frontend

- [ ] Add columns
- [ ] Add setting

## Documentation

- [ ] Update changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots
