### ISSUE TITLE
Hide metrics from report (including dashboard) by tag

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#7086]
# User story

As a quality manager I want to hide metrics from a report (including the dashboard) by tag(s) so I can send a report to stakeholders that only contains metrics they are interested in.

## Acceptance criteria

- [ ] Metrics that have a tag that is hidden are not visible in the dashboard and the subject.
- [ ] Subjects that become empty when hiding metrics by tag are not visible in the dashboard and not in the subject list.
- [ ] Visible/invisible tags are listed as url parameters.
- [ ] Visible/invisible tags are configurable via the Settings panel.
- [ ] Metrics without tags are always visible.

## Assumptions

- This functionality replaces or is merged with the current functionality to select a tag and hide metrics that don't have that tag.
- Unhiding tags is done via the Settings panel.

# Tasks

### Frontend

- [ ] Add all tags to the Settings panel. Each tag shows whether it is hidden or not, like we do for the columns already. Each tag can be hidden or shows individually.
- [ ] When a tag is hidden, don't show the tag card in the dashboard.
- [ ] When a tag is hidden, remove the metrics with that tag from their subject card.
- [ ] When a subject becomes empty, remove the subject from the subject list and from the dashboard.
- [ ] When a tag is hidden, add it to the (new) `hidden_tags` query parameter.
- [ ] Remove the existing `selected_tags` query parameter.

## Documentation

- [ ] Update changelog
- [ ] Update user manual
