### ISSUE TITLE
Hide all metrics

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#7211]
# User story

As a quality manager I want to hide all metrics so I can focus on the dashboard contents.

## Acceptance criteria

- [x] The "Visible metrics" column gets an extra menu item "No metrics". Clicking the menu item hides all metrics (and thus all subjects).
- [x] The dashboard still shows all metrics, subjects, and (visible) tags, regardless of the selection in the "Visible metric" column.
- [x] The "No metrics" option is added to the URL query parameters (so that export to PDF also works).

## Dependencies

- [x] Blocked by #7213.

# Tasks

### Frontend

- [x] Update settings menu
- [x] Update rendering of subjects

## Documentation

- [x] Update changelog
- [x] Add instruction to user manual
