### ISSUE TITLE
Allow for showing all metrics on the report overview page

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#7215]
# User story

As a quality manager I want show all metrics on the overview page so I can combine metrics from different reports.

## Acceptance criteria

- [x] Using the settings panel it is possible to show all metrics (or only metrics requiring action) from all reports on the reports overview page.
- [x] Filtering by tags works.
- [x] By default, all metrics are hidden on the reports overview page.
- [x] Metrics are grouped by subjects, like in the current tag report (so they get a title "Report > Subject".
- [x] Check that editing subjects, metrics, and sources works
- [x] Check that reordering subjects, metrics, and sources works
- [x] Reports overview can be exported to PDF via API.
- [x] Reports overview can be exported to PDF via UI.

## Out of scope

- Removing tag reports, see #7214.

## Dependencies

- [x] #7211 

# Tasks

### Frontend

- [x] Add Subjects to the reports overview page the same way they are added to tag reports.

### API server

- [x] Remove code specific to tag reports

### Shared code

- [x] Remove code specific to tag reports

## Documentation

- [x] Update changelog
- [x] Add instruction to user manual
