### ISSUE TITLE
Split source configuration into two parts visually: location and configuration

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#7489]
# User story

As a user I want to distinguish between configuring the location of a source and other source parameters so not all configuration parameters are displayed together.

## Acceptance criteria

- [ ] Split the configuration tab of sources into a location panel and a configuration panel. The location panel contains the location parameters: URLs, credentials, etc (these depend on the source type).
- [ ] Panels are lightweight: no borders and no title. Location panel is the bottom panel.

## Assumptions

- The report structure does not change.

## Out of scope

- Splitting the source into generic and specific parts, see #3127.

# Tasks

### Frontend

- [ ] Add two separate panels for location and configuration, based on what type parameters are in the data model.

### Shared code

- [ ] Move the location parameters (access parameters) in the data model to a separate `location_parameters` dict.

## Documentation

- [ ] Update changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots

Reported by @Sebastiaan127001

**Comment by wkoot** [comment]
Perhaps the spike #5241 from #4623 can be done here, before making changes twice
