### ISSUE TITLE
Create one issue for multiple measurement entities

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#7530]
# User story

As a quality manager I want to create one issue for multiple measurement entities at once because a developer will fix these measurement entities in one go.

## Acceptance criteria

- [ ] The issue text in Jira will have a list of links to the source (e.g. violations in SonarQube).
- [ ] The user can select a subset of the measurement entities and create an issue for that subset.

## Assumptions

- Something is present...

## Open issues

Possible implementation strategies:
- [ ] Select measurement entities with checkboxes and then apply the action to the selected entities. Question: where do we put the "Create issue" button? And how can the user enter one end date and rationale for all selected entities at once?
- [ ] Allow the user to group entities, for example by matching regular expressions. This adds an extra level in the entities table ("entity group"). Questions: how to deal with entities that match multiple regular expressions? How to deal with new entities in a group that already has an issue?

## Out of scope

- Refactoring ...
- Adding ...

# Tasks

### Frontend

- [ ] Add `user interface element`
- [ ] Update `user interface element`

### Shared code

- [ ] Change endpoint `endpoint`
- [ ] Extend the example reports
- [ ] Add subject `subject` to the data model
- [ ] Add metric `metric` to the data model
- [ ] Add source `source` to the data model
- [ ] Add logo for source `source`

### API-server

- [ ] Change endpoint `endpoint`
- [ ] Add ...

### Collector

- [ ] Change `collector`
- [ ] Add ...

### Notifier

- [ ] Change `destination`
- [ ] Add ...

## Feature tests

- [ ] `role` does `action`
- [ ] ...

## Documentation

- [ ] Update changelog
  - [ ] Describe change
  - [ ] Add deployment instructions to changelog
- [ ] Add instruction to user manual
- [ ] Update screenshots
- [ ] Update deployment instructions
- [ ] Update software documentation

Reported by @Sebastiaan127001
