### ISSUE TITLE
Time left notifications

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#7613]
# User story

As a quality manager I want to be notified of the time that is still left to address metrics so that I can have metrics fixed within the desired response times.

## Acceptance criteria

- [ ] Quality-time sends a daily notification (default 7 AM) with a list of metrics that will pass their desired response time within the next week.
- [ ] Metrics are sorted from least time left to most time left.

## Notification layout

Please address the following metrics:
 
`metric name` for `subject name` in `report title`. Status is `status_color` (`status`). Value is `value` `unit`. Time left to address: `time_left` days.

## Open issues

- Is it possible to have a better layout of the notifications? Maybe a table? Different colours for different statuses?

## Out of scope

- Configuration of the frequency and time of the notifications.

# Tasks

### API-server

- [ ] Change endpoint used by notifier to also include time left if necessary.

### Notifier

- [ ] Add notifications for time left

## Feature tests

- [ ] Add feature test if endpoint is changed.

## Documentation

- [ ] Update changelog
- [ ] Add instruction to user manual

Reported by @Sebastiaan127001
