### ISSUE TITLE
Show in the frontend when the collector is measuring a metric 

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#7760]
# User story

As a Quality-time user I want to see when the collector is measuring which metric so I know Quality-time is operating correctly.

## Acceptance criteria

- [ ] While the collector is working on a metric this is visible in the frontend.
- [x] The icon is not exported to the PDF.

# Tasks

### Frontend

- [ ] Parse the SSE messages for the metrics being measured.
- [ ] Add an icon with explanatory popup to the metric that the collector is working on.

### Database

- [ ] Add a MetricsBeingMeasured Collection

### Collector

- [ ] The collector adds the metrics it is working on to the MetricsBeingMeasured collection as soon as it starts measuring. When the collector has finished collecting its data it removes the metric from the MetricsBeingMeasured collection.
- [ ] In the SSE endpoint, add a list of metric (uuid)s being measured to each message.

## Documentation

- [ ] Update changelog

**Comment by fniessink** [comment]
When #3134 is implemented, Quality-time will show for edited metrics that they are not up-to-date (and by implication, that they are being measured). This makes this story largely obsolete.
