### ISSUE TITLE
Add a metric that is not listed as supported by the subject type

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#8176]
# User story

As a user I want to add a metric type to a subject that is not listed as supported by the subject type.

## Acceptance criteria

- [ ] When adding a metric using the "Add metric" button, the user can indicate that they want to see all metric types 
- [ ] After indicating that the user wants to add an unlisted metric, the user can choose all metric types.

## Assumptions

- Quality-time will not check that added metrics are listed as supported by the subject type (this is already not the case).

# Tasks

### Frontend

- [ ] Add a checkbox "Show all metric types" to the "Add metric dropdown menu"

## Documentation

- [ ] Update changelog

# Related issues

- #7992.
