### ISSUE TITLE
Allow for specifying supported versions of sources

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#8786]
# User story

As a user of Quality-time who configures sources I want to see which versions of the source are supported by Quality-time.

## Acceptance criteria

- [x] Quality-time shows the supported source version(s) in the source drop down for adding a source to a metric.
- [x] Quality-time shows the supported source version(s) after adding a source to a metric.
- [x] The Quality-time reference documentation contains the supported source version(s).
- [x] Documenting the supported source version is optional (otherwise we would have to document them all at once).

# Tasks

### Frontend

- [x] Show supported versions in the source drop down for adding a source to a metric, if available in the data model.
- [x] Add supported versions to the source configuration tab of metrics after adding a source, if available in the data model.

### Shared code

- [x] Add `supported_versions` to the `source` object in the data model

## Documentation

- [x] Update changelog
- [x] Update reference documentation to include supported source versions.
