### ISSUE TITLE
Force measurement of a metric

### ISSUE THREAD

**Issue by ds-o** [ICTU/quality-time#920]
# User story

As a user I want to see the new measurement value for a metric as soon as possible so that I know that the changes I made to the metric or source configuration or changes in the source give the expected results.

## Acceptance criteria

- [x] A user can force Quality-time to measure a metric as soon as possible.

## Assumptions

- ~~#7760 is implemented first, otherwise this feature would not provide any feedback to the user about what is happening.~~
- #3134 will imply that they are being measured. 

## Out of scope

- Showing that Quality-time is currently measuring a metric, see #7760.
- Showing that the config has changed and the current measurement value was measured with the old config, see #3134.

# Tasks

### Frontend

- [x] Add button "Measure now" next to the metric position buttons.
- [x] When the button is clicked, the frontend tells the API-server to remove the hash from the latest measurement of the metric.
- [x] Make the button inactive while the metric is being measured.

### Collector

- [x] Insert a new measurement after a measurement was requested, even if the measurement was not changed. This lets the frontend get a new measurement count via the number of measurements server-sent events end point so it knows the requested measurement was done.

### Shared code

- [x] Include a `measurement_requested` flag in the latest measurement summary so the frontend knows a measurement is pending.

## Feature tests

- [x] Add a scenario for requesting a measurement.
 
## Documentation

- [x] Update changelog

**Comment by fniessink** [comment]
I've created a separate issue for the error message timestamps: #980
