### ISSUE TITLE
Add a read-only source overview to each report

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#9214]
# User story

As a user I want to see what sources are used in the report so I can easily spot that I have configured the same source multiple times with different connection parameters.

## Acceptance criteria

- [ ] Report title contains an overview of sources. For each source, it shows the connection parameters and the list of metrics using the source.

## Out of scope

- Editing the sources.

# Tasks

### Frontend

- [ ] Add "Sources" tab to Report title with table of sources. Columns are source type, source name, and URL.
- [ ] Deduplicate sources 
- [ ] Don't show the sources without connection parameters, such as manual number
- [ ] Make sources expandable and show the connection parameters in the source details

## Documentation

- [ ] Update changelog

## Blocks 

- #3127
