### ISSUE TITLE
Throw error when entity keys are not unique

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#9883]
When entity keys are not unique, Quality-time may report the wrong count, see for example #9872. This story adds a feature to solve this problem for all sources.

# User story

As a quality manager I want Quality-time to warn me that my source has non-unique entity keys instead of reporting incorrect data so that I can fix the problem at the source or contact the Quality-time developers to fix the issue in Quality-time.

## Acceptance criteria

- [ ] Quality-time shows an exception when a source has entity keys that are not unique.

## Assumptions

- This can be implemented for all sources at once.

## Open issues

None so far.

## Out of scope

- Fixing any issues in the sources.

# Tasks

### Collector

- [ ] Check for duplicate entity keys before storing the measurement
- [ ] Throw an exception if there are any duplicate entity keys so that the message ends up in the UI.

## Documentation

- [ ] Update changelog
